[package]
name = "dn-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dn-lib = {path = "../dn-lib"}
clap = { version = "4.0", features = ["derive"] }