[package]
name = "bbk-dn-lib"
version = "0.1.0"
authors = ["tartasprint"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "dn_lib"
path = "src/lib.rs"

[dependencies]
