[package]
name = "dn-lib"
version = "0.0.0"
authors = ["tartasprint"]
edition = "2021"
license = "ISC"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "dnlib"
path = "src/lib.rs"

[dependencies]
thiserror = "1.0.40"
